### ISSUE TITLE
Can this be used in real time with microphone?

### ISSUE THREAD

**Issue by mattedminster** [snakers4/silero-models#1]
I am wondering if this can be used in real time with a microphone?

**Comment by snakers4** [comment]
Hi,

Technically speaking there is nothing preventing you from trying that. The model should work fine with decent audio from microphone.

But there are multiple facets to this:

- The model is just feed forward, and for proper operation / batching it is better to apply some VAD before the model (i.e. see TorchAudio bad);
- In terms of compute, current models should be fast enough to operate much faster than realtime on modern CPUs with proper feeding techniques, we will publish some benchmarks on commodity hardware;
- In terms of quality - there are similar domains in the train dataset;

**Comment by mattedminster** [comment]
Will give this a shot! thank you!

**Comment by snakers4** [comment]
As a first approximation this, together with VAD was added to colab example,
We are working on making tf-js work as well.

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/snakers4/silero-models/blob/master/examples.ipynb)
