### ISSUE TITLE
❓ Questions / Help / Support: Text enchancements fo RU lang

### ISSUE THREAD

**Issue by konstantin-sancom** [snakers4/silero-models#114]
## ❓ Questions and Help

Are there extra options available in `torch.hub.load` and in `apply_te` ?
Where I can find full list of options and description of how they affect punctuation restoration and capitalization processes?

**Comment by snakers4** [comment]
No, by design there are no custom settings and or options.
If the input is longer than ~150 words, it is chunked internally.
The model just works as-is, any pre- or post-processing should be done with text itself.

To think about it, I am not even sure, which options can there be?

**Comment by konstantin-sancom** [comment]
> No, by design there are no custom settings and or options. If the input is longer than ~150 words, it is chunked internally. The model just works as-is, any pre- or post-processing should be done with text itself.

Ok. I see.

> 
> To think about it, I am not even sure, which options can there be?

`Turning On/Off punctuation or capitalization` for example.

But it's ok. No extra options - ok.

**Comment by snakers4** [comment]
A flag for turning either one off is a nice idea, but same can be achieved with just `.lower` or a simple regex.
