### ISSUE TITLE
Bug report -problem loading STT model on Windows

### ISSUE THREAD

**Issue by lev007-ops** [snakers4/silero-models#121]
Hi, I decided to try selero_models, I do everything as in the dock, but I get an error. How to fix?

code:
```python
import torch
import zipfile
import torchaudio
from glob import glob

device = torch.device('cpu')  # gpu also works, but our models are fast enough for CPU
model, decoder, utils = torch.hub.load(repo_or_dir='snakers4/silero-models',
                                       model='silero_stt',
                                       language='en', # also available 'de', 'es'
                                       device=device)
```

Error:
RuntimeError                              Traceback (most recent call last)
C:\Users\E786~1\AppData\Local\Temp/ipykernel_9444/3004546653.py in <module>
      1 device = torch.device('cpu')  # gpu also works, but our models are fast enough for CPU
----> 2 model, decoder, utils = torch.hub.load(repo_or_dir='snakers4/silero-models',
      3                                        model='silero_stt',
      4                                        language='en', # also available 'de', 'es'
      5                                        device=device)

c:\PY\asistent\.venv\lib\site-packages\torch\hub.py in load(repo_or_dir, model, source, force_reload, verbose, skip_validation, *args, **kwargs)
    397         repo_or_dir = _get_cache_or_reload(repo_or_dir, force_reload, verbose, skip_validation)
    398 
--> 399     model = _load_local(repo_or_dir, model, *args, **kwargs)
    400     return model
    401 

c:\PY\asistent\.venv\lib\site-packages\torch\hub.py in _load_local(hubconf_dir, model, *args, **kwargs)
    426 
    427     entry = _load_entry_from_hubconf(hub_module, model)
--> 428     model = entry(*args, **kwargs)
    429 
    430     sys.path.remove(hubconf_dir)

~/.cache\torch\hub\snakers4_silero-models_master\hubconf.py in silero_stt(language, version, jit_model, **kwargs)
     32     assert language in available_languages
     33 
---> 34     model, decoder = init_jit_model(model_url=models.stt_models.get(language).get(version).get(jit_model),
     35                                     **kwargs)
     36     utils = (read_batch,

~/.cache\torch\hub\snakers4_silero-models_master\utils.py in init_jit_model(model_url, device)
    128                                        progress=True)
    129 
--> 130     model = torch.jit.load(model_path, map_location=device)
    131     model.eval()
    132     return model, Decoder(model.labels)

c:\PY\asistent\.venv\lib\site-packages\torch\jit\_serialization.py in load(f, map_location, _extra_files)
    159     cu = torch._C.CompilationUnit()
    160     if isinstance(f, str) or isinstance(f, pathlib.Path):
--> 161         cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
    162     else:
    163         cpp_module = torch._C.import_ir_module_from_buffer(

RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path: C:\Users\Дом/.cache\torch\hub\snakers4_silero-models_master\model\en_v5.jit

**Comment by snakers4** [comment]
Looks like a Windows-specific error.

(0)
Did the shell display any download progress indicator?

(1)
Does the path `C:\Users\Дом/.cache\torch\hub\snakers4_silero-models_master\model\en_v5.jit` exist on the fs?

(2)
I would suspect some of these lines to cause the error:
- https://github.com/snakers4/silero-models/blob/master/utils.py#L121-L123

**Comment by lev007-ops** [comment]
0 - yes, the indicator has reached 100

1 - this path exists on my computer

2 - why?

**Comment by snakers4** [comment]
>> RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path: C:\Users\Дом/.cache\torch\hub\snakers4_silero-models_master\model\en_v5.jit


> 2 - why?

It definitely has something to do with your env / how you run the script.
Does the error persist if you run the script from the console, as opposed to VSCode (I inferred it by the design of its windows)?

**Comment by lev007-ops** [comment]
> Does the error persist if you run the script from the console, as opposed to VSCode (I inferred it by the design of its windows)?
Yes

```python
C:\PY\asistent>c:/PY/asistent/.venv/Scripts/python.exe c:/PY/asistent/t.py
c:\PY\asistent\.venv\lib\site-packages\torch\package\_directory_reader.py:17: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  _dtype_to_storage = {data_type(0).dtype: data_type for data_type in _storages}
c:\PY\asistent\.venv\lib\site-packages\torchaudio\backend\utils.py:67: UserWarning: No audio backend is available.
  warnings.warn('No audio backend is available.')
Downloading: "https://github.com/snakers4/silero-models/archive/master.zip" to C:\Users\Дом/.cache\torch\hub\master.zip
100.0%
Traceback (most recent call last):
  File "c:\PY\asistent\t.py", line 8, in <module>
    model, decoder, utils = torch.hub.load(repo_or_dir='snakers4/silero-models',
  File "c:\PY\asistent\.venv\lib\site-packages\torch\hub.py", line 399, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "c:\PY\asistent\.venv\lib\site-packages\torch\hub.py", line 428, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\Дом/.cache\torch\hub\snakers4_silero-models_master\hubconf.py", line 34, in silero_stt
    model, decoder = init_jit_model(model_url=models.stt_models.get(language).get(version).get(jit_model),
  File "C:\Users\Дом/.cache\torch\hub\snakers4_silero-models_master\utils.py", line 130, in init_jit_model
    model = torch.jit.load(model_path, map_location=device)
  File "c:\PY\asistent\.venv\lib\site-packages\torch\jit\_serialization.py", line 161, in load
    cpp_module = torch._C.import_ir_module(cu, str(f), map_location, _extra_files)
RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path: C:\Users\Дом/.cache\torch\hub\snakers4_silero-models_master\model\en_v5.jit
```

**Comment by snakers4** [comment]
> RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path: C:\Users\Дом/.cache\torch\hub\snakers4_silero-models_master\model\en_v5.jit

> 1 - this path exists on my computer

Can you figure out, which would be the correct path in your case?
I.e. python clearly does not see this path. Can you fiddle around to find the correct path as seen by python interpreter?

I have never ran python on Windows, but I suspect  the problem may be with this part `Дом/.cache`.

Also I suspected that using `__file__` may [backfire](https://github.com/scikit-learn/scikit-learn/issues/20081), but people reported running on Windows before, so idk.

**Comment by lev007-ops** [comment]
> Can you figure out, which would be the correct path in your case?

and where does it usually lie?

**Comment by lev007-ops** [comment]
Along the path C:\Users\Дом\.cache\torch\hub\snakers4_silero-models_master, here is this folder

![image](https://user-images.githubusercontent.com/64062569/148781502-09e5d465-868c-4fb6-a02e-411651263be9.png)

**Comment by lev007-ops** [comment]
Can I manually download all models?

**Comment by lev007-ops** [comment]
@snakers4 

Even in the introduction, the error is

![image](https://user-images.githubusercontent.com/64062569/148785559-285a2990-4fc5-4820-b0a9-f6cd63f63ff9.png)

**Comment by snakers4** [comment]
If you try listing any of those paths from the python interpreter, does any of those work:

- `C:\Users\Дом/.cache\torch\hub\snakers4_silero-models_master\model\en_v5.jit`
- `C:\Users\Дом.cache\torch\hub\snakers4_silero-models_master`

What is the output of `torch.hub.get_dir()`?

**Comment by snakers4** [comment]
> Can I manually download all models?

`torch.hub` exists only for convenience. It only loads model files and imports utils listed in the `hubconf.py` file.

**Comment by snakers4** [comment]
Will close this for now
If this happens again, will try `importlib.resources`
