### ISSUE TITLE
Poll - which model hub do you use?

### ISSUE THREAD

**Issue by snakers4** [snakers4/silero-models#14]
Please vote under comments below

**Comment by snakers4** [comment]
TorchHub

**Comment by snakers4** [comment]
TF Hub

**Comment by snakers4** [comment]
ONNX models

**Comment by snakers4** [comment]
Other (please specify)

**Comment by federico-zb** [comment]
TF Hub

**Comment by snakers4** [comment]
https://github.com/onnx/models/pull/378

decided in the end not to go through in publishing through ONNX models hub
looks like their process is structured for submissions that are not designed to be actively maintained
also value in uploading everything to a third party resource entirely is questionable

**Comment by snakers4** [comment]
https://github.com/openvinotoolkit/open_model_zoo/issues/1622#issuecomment-702933944

most likely open vino zoo will also not work

**Comment by snakers4** [comment]
![image](https://user-images.githubusercontent.com/12515440/94990434-c68ec780-0584-11eb-811c-78f89871e73a.png)
![image](https://user-images.githubusercontent.com/12515440/94990440-cdb5d580-0584-11eb-8136-e014f3ba7e7c.png)
