### ISSUE TITLE
Bug report - RuntimeError: Unknown qengine

### ISSUE THREAD

**Issue by lik2129** [snakers4/silero-models#148]
Hello.
Great project! I would like to test a standard example, but  at the line:
model = torch.package.PackageImporter(local_file).load_pickle("tts_models", "model") 
I get an error:
\lib\site-packages\torch\jit\_script.py", line 351, in unpackage_script_module
   cpp_module = torch._C._import_ir_module_from_package(
untimeError: Unknown qengine

Python 10.4 , Torch 11.0 , device='cpu', Windows 10
Model:   torch.hub.download_url_to_file('https://models.silero.ai/models/tts/ru/ru_v3.pt',  local_file)  
Tell me, please, how to fix it?

**Comment by snakers4** [comment]
This is a well known problem due to your processor probably not having AVX2 instructions - https://github.com/snakers4/silero-models/discussions/104
We will remove quantized modules from the next release of the model

**Comment by lik2129** [comment]
Yes, you are right, mine Xeon X5670 does not support AVX2 .
Could you tell me, please, when such a model is planned?

**Comment by snakers4** [comment]
For other languages than Russian - soon (a week or two)
For Russian - when we improve our automated stress, maybe a month or two

**Comment by snakers4** [comment]
This also can be solved by trying to switch some PyTorch settings like quantizaton back-end, but sometimes it works, sometimes it does not

**Comment by lik2129** [comment]
It is interesting. Please give me a link in the documentation - I'll try)
I'll post what happened)

**Comment by snakers4** [comment]
Somewhere here - https://pytorch.org/docs/stable/quantization.html#introduction-to-quantization

**Comment by kamnsv** [comment]
> Это интересно. Дайте пожалуйста ссылку на документацию - попробую) выложу что получилось)

Получилось запустить в итоге?

**Comment by lik2129** [comment]
Привет. 
К сожалению не смог разобраться. 
Я рассчитывал найти опцию при которой бы метод 
'torch.hub.download'  смог бы загрузить модель.....
Но ничего не обнаружил.

**Comment by lik2129** [comment]
Если чем то могу помочь с созданием новой версии с удовольствием подключусь)
Квантование, как я понял, это полезно для моделей - уменьшает ее размеры и немного ускоряет.
Хорошо бы создать квантованную модель, работающую на старых процессорах.....)

**Comment by snakers4** [comment]
Мы уберем квантизацию в следующем релизе
Там квантизована была не основная модель
Но мы решили свои вопросы по скорости

**Comment by lik2129** [comment]
Ок. Спасибо. Очень жду)

**Comment by lik2129** [comment]
Привет.
torch.hub.download_url_to_file - у меня все так же выдает ошибку.
from silero import silero_tts - успешно
Только как теперь получить локальную модель?
silero_tts.to(device) - выдало ошибку: 'function' object has no attribute 'to'

**Comment by snakers4** [comment]
> Только как теперь получить локальную модель?

Можно посмотреть url в файле models.yml и скачать вручную

Касательно остального, нового релиза пока не было

**Comment by snakers4** [comment]
В новой версии `v3_1_ru` по идее нет явно квантизованных моделей, там это делается немного более хитро. 
Можно проверить вызывает ли это такую же ошибку.
Если вызывает - открывайте новый тикет.
