### ISSUE TITLE
Need help with the Silero and Torch library.

### ISSUE THREAD

**Issue by Lunch01** [snakers4/silero-models#154]
### Need help with the Silero and Torch library.
**Libraries used: Torch and Silero**
_I'm building an artificial voice assistant_ on the **silero** and **torch** library. After installing the libraries. I enter a variable in the code:
device = torch.device(0). Then it gives an error: 
    device = torch.device(0)
AttributeError: module 'torch' has no attribute 'device'. Of course, I know what to google and I did it, but in the answer it was said to update the **torch** library. I updated to the latest, same error. I remember trying to do the same again. **Silero** needed a specific version of the **torch**. Can you tell me why and how to solve this problem?

**Comment by snakers4** [comment]
Please read the pytorch docs regarding the device management properly:

https://pytorch.org/docs/stable/notes/cuda.html#best-practices

This seems unrelated to our models.
