### ISSUE TITLE
README's Standalone Use misses to mention NumPy

### ISSUE THREAD

**Issue by procedural** [snakers4/silero-models#163]
Currently, https://github.com/snakers4/silero-models#standalone-use states that:

> * Standalone usage just requires PyTorch 1.10+ and python standard library;

but I had to install NumPy as well to make the example work.

**Comment by snakers4** [comment]
> but I had to install NumPy as well to make the example work.

Typically, NumPy is a dependency of PyTorch, among others, and they are installed together.

Are you installing / compiling PyTorch from source?
This may explain

**Comment by procedural** [comment]
> Typically, NumPy is a dependency of PyTorch, among others, and they are installed together (this is the reason we do not list NumPy).

It wasn't installed on my machine after I installed PyTorch with `python -m pip install torch` on Windows 10, so I also had to manually install numpy with `python -m pip install numpy`.

**Comment by snakers4** [comment]
I see.
Do you remember maybe which line in the code caused the error?
I remember doing some operations on tensors in TTS, but I do not remember importing NumPy explicitly.

**Comment by procedural** [comment]
I don't remember, but to repro I temporarily uninstalled numpy and ran the script again, and I think the error looks like the one I saw the first time:
```
C:\Users\Constantine\Desktop>python script.py
C:\hostedtoolcache\windows\Python\3.10.2\x64\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
Traceback (most recent call last):
  File "C:\Users\Constantine\Desktop\script.py", line 19, in <module>
    audio_paths = model.save_wav(text=example_text, speaker=speaker, sample_rate=sample_rate)
  File "<torch_package_0>.multi_acc_v3_package.py", line 373, in save_wav
RuntimeError: Numpy is not available
```

**Comment by snakers4** [comment]
> At which line, or in place of what? I don't code in python or these libraries much, I'm just a random guy. 😁

```
import torch

language = 'ru'
model_id = 'v3_1_ru'
sample_rate = 48000
speaker = 'xenia'
device = torch.device('cpu')

model, example_text = torch.hub.load(repo_or_dir='snakers4/silero-models',
                                     model='silero_tts',
                                     language=language,
                                     speaker=model_id)
model.to(device)  # gpu or cpu

audio = model.apply_tts(text=example_text,
                        speaker=speaker,
```

**Comment by snakers4** [comment]
model has `apply_tts` and `save_wav` methods

**Comment by procedural** [comment]
So with
```py
import torch

language = 'ru'
model_id = 'v3_1_ru'
sample_rate = 48000
speaker = 'xenia'
device = torch.device('cpu')

model, example_text = torch.hub.load(repo_or_dir='snakers4/silero-models',
                                     model='silero_tts',
                                     language=language,
                                     speaker=model_id)
model.to(device)  # gpu or cpu

audio = model.apply_tts(text=example_text, speaker=speaker, sample_rate=sample_rate)
```
it throws this:
```
C:\Users\Constantine\Desktop>python script.py
C:\hostedtoolcache\windows\Python\3.10.2\x64\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
Downloading: "https://github.com/snakers4/silero-models/archive/master.zip" to C:\Users\Constantine/.cache\torch\hub\master.zip
Traceback (most recent call last):
  File "C:\Users\Constantine\Desktop\script.py", line 9, in <module>
    model, example_text = torch.hub.load(repo_or_dir='snakers4/silero-models',
  File "C:\hostedtoolcache\windows\Python\3.10.2\x64\lib\site-packages\torch\hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.10.2\x64\lib\site-packages\torch\hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\Constantine/.cache\torch\hub\snakers4_silero-models_master\src\silero\silero.py", line 51, in silero_tts
    from omegaconf import OmegaConf
ModuleNotFoundError: No module named 'omegaconf'
```

**Comment by snakers4** [comment]
Torch hub pulls omegaconf, right, we did not cut it everywhere.

Try this then:

```
import os
import torch

device = torch.device('cpu')
torch.set_num_threads(4)
local_file = 'model.pt'

if not os.path.isfile(local_file):
    torch.hub.download_url_to_file('https://models.silero.ai/models/tts/ru/v3_1_ru.pt',
                                   local_file)  

model = torch.package.PackageImporter(local_file).load_pickle("tts_models", "model")
model.to(device)

example_text = 'В недрах тундры выдры в г+етрах т+ырят в вёдра ядра кедров.'
sample_rate = 48000
speaker='baya'

audio = model.apply_tts(text=example_text, speaker=speaker, sample_rate=sample_rate)
```

**Comment by snakers4** [comment]
But it produces the tensor, right?

**Comment by procedural** [comment]
> Torch hub pulls omegaconf, right, we did not cut it everywhere.

omegaconf reminds me of omegastar 😁 

[![](https://img.youtube.com/vi/y8OnoxKotPQ/0.jpg)](https://www.youtube.com/watch?v=y8OnoxKotPQ)

**Comment by procedural** [comment]
> But it produces the tensor, right? This looks like a warning

Where exactly? What I should look for? No .wav's on the Desktop folder, or should I look for something else?

**Comment by procedural** [comment]
> You can print (to make sure it worked) it or pass to some audio player.

I can do that, just with `print(audio)`, right?

**Comment by procedural** [comment]
So with `print(audio)` added, it outputs this:
```
C:\Users\Constantine\Desktop>python script.py
C:\hostedtoolcache\windows\Python\3.10.2\x64\lib\site-packages\torch\_masked\__init__.py:223: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  example_input = torch.tensor([[-3, -2, -1], [0, 1, 2]])
tensor([-0.0064, -0.0064, -0.0064,  ..., -0.0013, -0.0042,  0.0033])
```

**Comment by snakers4** [comment]
So it generates audio,
I will keep in mind that NumPy is required for `save_wav`.
In any case I believe your problem is solved.

**Comment by procedural** [comment]
Cool, thanks, @snakers4!

**Comment by procedural** [comment]
"Wow, double close! Double close all the way!" 😁

**Comment by AXKuhta** [comment]
I have something to add! I've tackled this issue in my TTS server script: https://github.com/AXKuhta/silero_tts_server/blob/99f9e2c809b2f1bfd58e1f97263cc2235c7af11a/server.py#L44-L46

This removes dependency on `numpy` in favor of the `array` module, which is a part of python.

**Comment by VictorKolb** [comment]
> ```python
> import os
> import torch
> 
> device = torch.device('cpu')
> torch.set_num_threads(4)
> local_file = 'model.pt'
> 
> if not os.path.isfile(local_file):
>     torch.hub.download_url_to_file('https://models.silero.ai/models/tts/ru/v3_1_ru.pt',
>                                    local_file)  
> 
> model = torch.package.PackageImporter(local_file).load_pickle("tts_models", "model")
> model.to(device)
> 
> example_text = 'В недрах тундры выдры в г+етрах т+ырят в вёдра ядра кедров.'
> sample_rate = 48000
> speaker='baya'
> 
> audio = model.apply_tts(text=example_text, speaker=speaker, sample_rate=sample_rate)
> ```

Still not working

**Comment by VictorKolb** [comment]
> We will fix it with next releases. Many thanks.

Still not working
