### ISSUE TITLE
Feature request - Expressiveness

### ISSUE THREAD

**Issue by X-Ryl669** [snakers4/silero-models#164]
## 🚀 Feature
Right now, in French STT, there is no decay upon a end of sentence. So if you have 2 sentences, the prosody is wrong and painful to hear. Each sentence by itself is almost perfect, but upon the end of a sentence, the pitch should decrease, the rate should also decrease and a short pause is required before starting a new sentence.

## Motivation
This is useful as soon as you have more than 2 sentences to synthetize. Else, the current, excellent quality of the STT engine is useless, since no human speaks continuously across sentences.

**Comment by snakers4** [comment]
Hi,

Do you use SSML or just pass 2 sentences separated by a full stop?

Can you post and example?

**Comment by X-Ryl669** [comment]
I've tried both case and it's the same. I'm using [this](https://colab.research.google.com/github/snakers4/silero-models/blob/master/examples_tts.ipynb) by replacing `v3_1_ru` by `v3_fr` and the speaker by `fr_0`. It seems the model doesn't have any feature for end of sentence.

**Comment by snakers4** [comment]
```
ssml_sample = """
              <speak>
              <s>Le français est la sixième langue la plus parlée au monde après le chinois, l’anglais, le hindi, l’espagnol et l’arabe.</s>
              <s>Elle est également la deuxième langue la plus apprise sur le globe.</s>
              </speak>
              """

sample_rate = 24000
speaker = 'fr_3'              
audio = model.apply_tts(ssml_text=ssml_sample,
                        speaker=speaker,
                        sample_rate=sample_rate)
display(Audio(audio, rate=sample_rate))
```

The simple solution is to use `<p>` and `<s>` tags. This introduces slight artefacts sometimes, and some speakers sound better than others with regard to intonation. 

We did not really curate the French dataset with regard to long / short sentences, but most likely this issue is data related.

**Comment by X-Ryl669** [comment]
Thanks for the tip, but that doesn't seem to make a change. There's still no pause and the slight "descent" on sentence's end. For example, when using some random STT online, we get [this](https://vttts.readspeaker.com/cgi-bin/nph-voicetext/91488a1eb535ce565c50805ca5c161c1.mp3), please notice the end of the sentence and the small pause between sentences.

**Comment by snakers4** [comment]
> There's still no pause and the slight "descent" on sentence's end
> please notice the end of the sentence and the small pause between sentences.

The pause can be handled just by iterating over sentences.

The intonation is usually handled on case by case basis, we did not really invest any commercial resources into these voices, let alone record any proper high quality voices.

Though I believe that we will create some upstream features for all voices (like question intonation), this can only be properly fixed only by recording a proper dataset, but that usually cannot be published for commercial projects.

If you compare how properly recorded voices sound (like `xenia` in `v3_1_ru`), you can hear this difference:

- [xenia.zip](https://github.com/snakers4/silero-models/files/8941387/xenia.zip)

> For example, when using some random STT online

While I really appreciate your input regarding the assessment of the naturalness of the TTS, I do not believe this is just some "random STT" (TTS?),  this is a venture backed subsidiary of a Japanese corporation.

So probably the gap in the resources used to create these may be up to 2 or 3 orders of magnitude. Also note that our models are downloadable and work on 1 CPU thread.

**Comment by X-Ryl669** [comment]
Ah. I thought that was something that could be fixed in the last encoding step (as a pseudo algorithm, if end of sentence with a dot, let's decrease the pitch for the last syllable, and add a silence of 200ms, if it's a question mark, let's increase the pitch and add a silence etc...).  I've seen you are supporting the pitch & rate parameter in the SSML format, so I guessed wrongly that that could be tuned without changing the model's itself.

I didn't know you need to train the model for this specific feature.

BTW, the russian example it a lot better, although I don't speak russian there are clear delimitation between sentences.

I guess it's not possible to add more data to the model to train it in French ?

**Comment by X-Ryl669** [comment]
Tried this and it's a lot better (in my humble opinion):
```py
ssml_sample = """
              <speak>
              <p>
                  Le français est la sixième langue la plus parlée au monde après le chinois, l’anglais, le hindi, l’espagnol et l'a<prosody pitch="x-low">rabe.</prosody>.
                  <break time="400ms"/>. Elle est également la deuxième langue la plus apprise dans le <prosody pitch="x-low">monde</prosody></p>
              <break time="600ms"/>.
              <p>Comment pourriez vous créer une meilleure <prosody pitch="x-high">version?</prosody></p>
              </speak>
              """
```

**Comment by snakers4** [comment]
> I've seen you are supporting the pitch & rate parameter in the SSML format, so I guessed wrongly that that could be tuned without changing the model's itself.
> I didn't know you need to train the model for this specific feature.

The pitch and speed can manually controlled, but if you set them manually, some artefacts appear.
Hence there already are some hacks interpolating pitch for pauses, which were fine-tuned on better voices.


> BTW, the russian example it a lot better, although I don't speak russian there are clear delimitation between sentences.
> I guess it's not possible to add more data to the model to train it in French ?

The only guaranteed way we know is to record a proper dataset with a proper speaker, which is a small project and / or curate the existing datasets, some of which were repurposed for TTS.

**Comment by X-Ryl669** [comment]
That makes sense. Thanks a lot for the explanation.
