### ISSUE TITLE
Bug report - [RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path] Windows 10

### ISSUE THREAD

**Issue by s1zen** [snakers4/silero-models#165]
## 🐛 Bug Windows 10 Python 3.9.13
Using cache found in C:\Users\Тимур/.cache\torch\hub\snakers4_silero-models_master
Traceback (most recent call last):
  File "C:\Users\Тимур\Desktop\projects\ml&ai\main.py", line 9, in <module>
    model, example_text = torch.hub.load(repo_or_dir='snakers4/silero-models',
  File "C:\Users\Тимур\Desktop\projects\ml&ai\venv\lib\site-packages\torch\hub.py", line 404, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "C:\Users\Тимур\Desktop\projects\ml&ai\venv\lib\site-packages\torch\hub.py", line 433, in _load_local
    model = entry(*args, **kwargs)
  File "C:\Users\Тимур/.cache\torch\hub\snakers4_silero-models_master\src\silero\silero.py", line 87, in silero_tts
    imp = package.PackageImporter(model_path)
  File "C:\Users\Тимур\Desktop\projects\ml&ai\venv\lib\site-packages\torch\package\package_importer.py", line 75, in __init__
    self.zip_reader = torch._C.PyTorchFileReader(self.filename)
RuntimeError: open file failed because of errno 2 on fopen: No such file or directory, file path: C:\Users\Тимур/.cache\torch\hub\snakers4_silero-models_master\src\silero\model\v3_1_ru.pt

code: 
import torch

language = 'ru'
model_id = 'v3_1_ru'
sample_rate = 48000
speaker = 'xenia'
device = torch.device('cpu')

model, example_text = torch.hub.load(repo_or_dir='snakers4/silero-models',
                                     model='silero_tts',
                                     language=language,
                                     speaker=model_id)
model.to(device)  # gpu or cpu

audio = model.apply_tts(text=example_text,
                        speaker=speaker,
                        sample_rate=sample_rate)

**Comment by snakers4** [comment]
> C:\Users\Тимур/.cache\torch\hub\snakers4_silero-models_master\src\silero\model\v3_1_ru.pt

Does this path exist on your filesystem?

We do not usually test anything on windows, so to be honest I do not know why this happens. 

Most likely somewhere in torch hub code the path is handled incorrectly, windows always has some peculiarities. Or maybe something about your env, idk.

As a workaround - do standalone examples, i.e. without torch.hub help?

**Comment by snakers4** [comment]
https://github.com/snakers4/silero-models#standalone-use

**Comment by s1zen** [comment]
Hi, let it exist, this example works successfully, I'll go install a virtual machine

**Comment by snakers4** [comment]
Please submit a PR if you find a root cause of the problem.
If the standalone example works, let's mark it as solved.
