### ISSUE TITLE
Add Italian TTS

### ISSUE THREAD

**Issue by albanobattistella** [snakers4/silero-models#168]
Hello,

We ask if is possible to add italian language.
thanks.
A.

**Comment by snakers4** [comment]
TTS?

**Comment by albanobattistella** [comment]
> TTS?

Yes.

**Comment by snakers4** [comment]
When choosing the languages to cover in the public release, we mostly tried to choose the widely spoken languages that have some available data + some languages from the CIS:

- English - global language;
- French - Africa;
- Spanish - Latin America; 
- Indic languages - India;

If we were planning it now probably we would exclude German, but there was a too high quality dataset avaiable, the model could be useful for us for transfer learning.

So the answer is - yes, of course it is possible, but only on commercial basis.

**Comment by snakers4** [comment]
For commercial inquiries please email us directly or DM me in telegram.
