### ISSUE TITLE
Add Czech STT and TTS

### ISSUE THREAD

**Issue by tibor-vavra** [snakers4/silero-models#169]
Hi,
I love your project. 

Is it possible to add a Czech language model for TTS and STT?

Thank you

**Comment by snakers4** [comment]
Yes, but only on commercial basis

**Comment by tibor-vavra** [comment]
Ok, but what does that mean exactly? I'm interested in both TTS and STT for the Czech language. You can write me a personal email if you don't want to write it here publicly.

Thank you

**Comment by snakers4** [comment]
For commercial inquiries please email us directly or DM me in telegram.
