### ISSUE TITLE
Feature request - [New German Data Set Thorsten – 2022.10 Available for Re-Training

### ISSUE THREAD

**Issue by eqikkwkp25-cyber** [snakers4/silero-models#190]
Are there any plans to re-train and provide a new model based on the new German data set Thorsten 2022.10 
which can be found here [https://www.thorsten-voice.de/en/datasets-2/](https://www.thorsten-voice.de/en/datasets-2/)
 
Thanks.

**Comment by snakers4** [comment]
No plans yet
