### ISSUE TITLE
TE Model for GPU

### ISSUE THREAD

**Issue by PhenomenalOnee** [snakers4/silero-models#193]
Really Nice Work there. I am testing the text enhancement model "v2_4lang_q.pt" using example_te.ipynb but i cant load the model in GPU i can use the model with cpu. Any idea why.
I am using this line to load model in cuda:
imp = package.PackageImporter(model_path)
model = imp.load_pickle("te_model", "model", map_location='cuda')
when i use cpu in map_location it works

**Comment by snakers4** [comment]
Hi,
This model was designed to run on CPU only.
