### ISSUE TITLE
Issue getting from silero model tried for text enhancement

### ISSUE THREAD

**Issue by Kishan-Sahu** [snakers4/silero-models#201]
### Issue
 File "<torch_package_104>.release_module.py", line 122, in enhance_text
  File "<torch_package_104>.release_module.py", line 101, in enhance_long_textblock
  File "<torch_package_104>.release_module.py", line 72, in enhance_textblock
  File "<torch_package_104>.release_module.py", line 165, in enhance_tokens
IndexError: string index out of range

### Details
I added punctuation to the text using Silero models over the PyTorch hub, and everything was going smoothly until the attached text example appeared. I have no idea why this is occurring.
I'm using this model to add punctuation to transcripts that I collect from YouTube; some of them have a few missing punctuation marks (supplied by the video author), while others have no punctuation at all (auto-generated by youtube).

### Transcript throwing Error
transcript 1: ""Hey there. How's it going everybody in this video? We'll be learning about python Data types and specifically We'll be learning about how to work with textual data and textual data in python are represented with strings So we currently have [opened] our intro pi file that we were working with in the last video Where we just printed out hello world and I'll go ahead and run this so that we can see that down here It does print out hello [world] [now] This line here is using the print function and we're passing this text value into that print function now if we wanted to create a Variable that holds that text value then we could say now I'll just get rid of this comment for now So if I wanted a variable to hold that value then I can just create a variable and we'll call that"

transcript 2: "you're now ready to see how to go one layer of a convolution on your network let's go through the example you've seen in the previous video how to take a 3d volume and convolve it with say two different filters in order to get in this example two different 4x4 outputs so let's say convolving with the first filter gives this first 4x4 output and convolving with this second filter gives a different 4x4 output the final thing to turn this into a convolutional neural net layer is that for each of these we're going to add it bias so this is going to be a real number and what - broadcasting you kind of had the same number - every you know one of these sixteen elements and then apply a non-linearity which for illustration that says there a luna mini arity and this gives you a 4x4 output after applying the bias and the non-linearity and then for this thing at the bottom as well you had some different buyers again this is a real number so you had the same row number - all 16 numbers and then applies some non-linearity that fairly non-linearity and this gives you a different 4x4 output then same as we did before if you take this and stack it up as follows so they end up with a 4 by 4 by 2 output then this computation where you've gone from 6 by 6 by 3 to a 4 by 4 by 4 this is one layer of a convolutional neural network Center mapped is back to one layer of for propagation in the standard neural network when a non convolutional neural network remember that one step afford prot was something like this right z1 equals w1 times a0 a0 was also equal to X right and then plus b1 and he applied the non-linearity to get a 1 so that's G of Z 1"
Please review the above transcript that is and let us know what the problem is.

**Comment by snakers4** [comment]
Can you try the same text, lowercase w/o any punctuation?

**Comment by Kishan-Sahu** [comment]
Thank you for your response. I tested the following example and a few more, and it works fine. However, is there any way to avoid eliminating existing punctuation and capital letters?

**Comment by snakers4** [comment]
Currently not, you have to store the existing caps / punctuation manually and decide which you like more, the original or new / and or combine them.

**Comment by Kishan-Sahu** [comment]
okay, thanks, where to make changes if I want the original one?

**Comment by Kishan-Sahu** [comment]
The model runs successfully on the above text after removing all alphanumeric characters.
