### ISSUE TITLE
Model getting stuck on some texts.

### ISSUE THREAD

**Issue by Kishan-Sahu** [snakers4/silero-models#202]
There **hasn't been a debugging message** to explain why the model keeps getting stuck for a very long period. Please assist us in adding a debugging message to the model so we can identify the cause of the problem.

The text for which the model stuck is given below:

Text: "we're going to set this by saying export Python path all uppercase and then equals and now we want to set that location so I'm just going to come over here and grab that location and paste that in those quotes and we want it to look just like that no space in between the equals and the path so to save that we can just hit ctrl X and then Y to save and then enter to keep the same file name and now we can either restart our terminal or run a source command on that file but I'll just restart the terminal here and pull this up and now if we run Python then let's see if we can import that module so import my module and we can see that that worked and the reason that worked is that if we import sis and look at our sis then we can see that after our current directory that we have the directory that was added there and the reason that it's added is that we added it to our Python path environment variable so now let's take a look at how to set"

I manually tested by eliminating strange letters and words and discovered that removing **"ctrl"** from text, worked effectively.

**Comment by snakers4** [comment]
Does this help?
https://github.com/snakers4/silero-models/issues/183
