### ISSUE TITLE
Can we use this to generate speech from subtitle file? srt or vtt

### ISSUE THREAD

**Issue by FurkanGozukara** [snakers4/silero-models#205]
Hello. I want to fully replace my older video sounding by providing a manually fixed srt / vtt file

I am generating transcription by using Whisper

I am then manually fixing the file

Example video and srt file I have. So how can I use this model?

C# Expert OOP - Lecture 1: Classes, Methods, Access Modifiers, Static, IDE, DLL, Fields & Properties
https://youtu.be/s-FZ2pW6UF4

[captions (3).txt](https://github.com/snakers4/silero-models/files/10712166/captions.3.txt)

send an email from my school email furkan . gozukara at toros edu tr

**Comment by snakers4** [comment]
For tts just follow the readme.
For whisper - this is not our product.
