### ISSUE TITLE
How to disable "Using cache" print

### ISSUE THREAD

**Issue by ParthenGithub** [snakers4/silero-models#218]
## ❓ Questions and Help

Every time I give silero some line to voice, it prints "Using cache found in C:\Users\user/.cache\torch\hub\snakers4_silero-models_master"
How I can disable this?

**Comment by snakers4** [comment]
Does this occur when you are loading the model?

**Comment by ParthenGithub** [comment]
Yeah

**Comment by snakers4** [comment]
Then this is pytorch, not us. You can cache the models manually anyway.
