### ISSUE TITLE
Expected changes in `torchaudio.load`

### ISSUE THREAD

**Issue by mthrok** [snakers4/silero-models#25]
Hi

Thanks for using `torchaudio`. We are overhauling I/O mechanism, and in the future, the signature of `torchaudio.load` will be slightly changed.  The detail can be found https://github.com/pytorch/audio/issues/903

In the following use case, `normalization` becomes `normalize`, but the default value will be kept same.

https://github.com/snakers4/silero-models/blob/15d36e482b70e20c876a448f5beb628fe8903347/utils.py#L29-L31

In the upcoming release `0.7.0`, (which is expected to happen in about a week), we start issuing warnings about the change, but the code will keep working. In `0.8.0` release (no fixed date yet), the interface will be changed.
Since the default values for `normalization`/`normalize` and `channels_first` are kept same, using `wav, sr = torchaudio.load(path)` will reduce the maintenance cost.

**Comment by snakers4** [comment]
Hi,

Many thanks for the heads up!
Fixed this https://github.com/snakers4/silero-models/commit/046cccdcb62a48a151a0a40fbba0e7a4537b69a9
Gave it a quick test in the colab, seems to be fine

**Comment by mthrok** [comment]
The change looks good!
