### ISSUE TITLE
В v4_ru двоится голос у Баи и Ксении

### ISSUE THREAD

**Issue by PopkovS** [snakers4/silero-models#250]
В v4_ru двоится(ну или типо робовойсит) голос у Баи и Ксении(другими не пользуюсь)
в v3_ru такой проблемы нет(там правда иногда были проблемы с произношением некоторых слов, "все" например произносилось как "всё" и не только, в 4й такого нет)

видеокарта  1060 6гб

Пробовал и с cuda и с cpu
код стандартный из примера 
```
audio_paths = self.model.save_wav(ssml_text=blok,
                                              speaker=f"{self.speaker_number}",
                                              sample_rate=24000,
                                              audio_path=fr"{self.audio_path}\{self.raw_title}-{str(num + 1)}.wav")
```

(текст всё ровно подкидываю с "+" ударениями, у меня уже так процесс налажен, надеюсь с этим не связанно)
sample_rate - менять пробовал 

https://github.com/snakers4/silero-models/assets/19222739/f8ee55b4-f58e-4d42-915a-1ae6020bc798

**Comment by Tessory** [comment]
Тоже столкнулся с ухудшением в звучании Xenia на моделе v4. На v3.1 абсолютно та же фраза звучит намного лучше.
v4 порой звучит с эхом на некоторых фразах.
Сравнение

https://github.com/snakers4/silero-models/assets/147715102/f8772a58-d452-4fba-9971-9b3db73377a2

**Comment by snakers4** [comment]
Модели с максимально качественным звучанием доступны через наш бот в Телеграме или на коммерческой основе.
Решение о таком разделении публичных и приватных моделей было принято после многократных нарушений лицензии модели и коммерческого использования публичных моделей вопреки лицензии.

**Comment by PopkovS** [comment]
@snakers4 
А как купить себе нормальную четвертую версию, возможно вопрос очень глупый, но это реально очень плохо гуглится.
Можно ссылку или типо того)

**Comment by Tessory** [comment]
Печально слышать, но надеюсь, что не прикроете такой прекрасный проект с публичными моделями. Телеграм это хорошо, но он никогда не будет проще локальной генерации. Надеюсь, что публичную версию допилите, чтобы она не двоилась и в эхо не уходила.
