### ISSUE TITLE
Bug report - load() missing 1 required positional argument: 'repo_or_dir'

### ISSUE THREAD

**Issue by martinoywa** [snakers4/silero-models#26]
## 🐛 Bug

This issue occurs when trying to run the code snippet for PyTorch in the README.md file.

![0ne](https://user-images.githubusercontent.com/33571053/97427385-7c9bc600-1925-11eb-8654-16dcce846972.png)

## Expected behavior

From the PyTorch documentation https://pytorch.org/docs/stable/hub.html#loading-models-from-hub,
**torch.hub.load** takes these parameters **repo_or_dir**, **model**, ***args**, ****kwargs**, and no **github**.

## Fix
Update the code to the following;
```
model, decoder, utils = torch.hub.load(repo_or_dir='snakers4/silero-models',
                                       model='silero_stt',
                                       language='en', # also available 'de', 'es'
                                       device=device)
```
![two](https://user-images.githubusercontent.com/33571053/97427420-87eef180-1925-11eb-9634-3bf40508e87f.png)

## Environment
```

 - PyTorch Version: 1.6
 - OS: Linux
 - How you installed PyTorch: conda
 - Python version: 3.8.3
 - CUDA/cuDNN version: 11.0

**Comment by snakers4** [comment]
Hi,

Many thanks for reporting this.

>  - PyTorch Version: 1.6

Looks like in 1.7 they just changed this method.
I will fix it shortly.
Looks like I need also to make a PR in the Torch hub.

**Comment by martinoywa** [comment]
> Hi,
> 
> Many thanks for reporting this.
> 
Pleasure's all mine!
