### ISSUE TITLE
❓ Questions / Help / Support

### ISSUE THREAD

**Issue by hellcezar** [snakers4/silero-models#276]
## ❓ Questions and Help

Can i set speak speed in settings of speaker? like xenia - x-fast?
im do some mode of synth voice from file, and i need to set speaking speed, thx

Можно ли выставить скорость синтеза речи в настройках говорящего ? Т.к я модифицировал код для своих нужд, что бы заливать файлы и озвучивать их, но вот как выставить скорость для всего синтеза - не разобрался. Спасибо!

We have a [wiki](https://github.com/snakers4/silero-models/wiki) available for our users. Please make sure you have checked it out first.

**Comment by snakers4** [comment]
Нет, только через SSML.
