### ISSUE TITLE
❓ Help: Could you please help on an issue while exporting models to ONNX?

### ISSUE THREAD

**Issue by fatcat-z** [snakers4/silero-models#50]
I've tried to run the model with en/de/es succssfully, and we want to export the models to ONNX file for running with onnxruntime.

Unfortunately, in Ubuntu + PyTorch 1.7.1 + Python 3.8.5, the torch.onnx.export() functions failed and threw an exception with errors below:

**_temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="num_batches_tracked"](%4243, %4373)_**

The code looks like below:

        model, _, utils = torch.hub.load(github, model_name, language=language_name)
        model.eval()
        (read_batch, split_into_batches, _, prepare_model_input) = utils 

        # download a single file, any format compatible with TorchAudio (soundfile backend)
        torch.hub.download_url_to_file('https://opus-codec.org/static/examples/samples/speech_orig.wav',
                                        dst = 'speech_orig.wav', progress=True)
        test_files = glob('speech_orig.wav')
        batches = split_into_batches(test_files, batch_size=10)
        input_tensor = (prepare_model_input(read_batch(batches[0])), )
        if torch.cuda.is_available():
            model.to('cuda')
            if isinstance(input_tensor, tuple):
                new_tensor = [x.to('cuda') for x in input_tensor]
                input_tensor = tuple(new_tensor)
            else: 
                input_tensor = input_tensor.to('cuda')
        torch.onnx.export(model, input_tensor, 'my_model.onnx', verbose=False, opset_version=12)

I also noticed that you have already prepared some ONNX files for these models. So, is it possible that you can share with me how you export those files successfully? With any special scripts?

Thanks!

**Comment by snakers4** [comment]
Hi,

> and we want to export the models to ONNX file for running with onnxruntime.

What is wrong with the provided ONNX checkpoints?

https://github.com/snakers4/silero-models/blob/master/models.yml#L10
https://github.com/snakers4/silero-models/blob/master/models.yml#L35
https://github.com/snakers4/silero-models/blob/master/models.yml#L44

> The code looks like below:

Not sure I can replicate this, but typically ONNX export requires enumerations of input / output axes and I have not tried doing this with GPU tensors
