### ISSUE TITLE
Feature request - SAPI5

### ISSUE THREAD

**Issue by studennikov-serg** [snakers4/silero-models#57]
SAPI5 compatibility
## Motivation
Mostly enough for screen readers (Windows).
But this interface is for integration by its nature.
Ready to help!

**Comment by snakers4** [comment]
This feature sounds very important for people with sight impairments.
I have also contacted RHvoice developers, maybe they also will lend a hand.
The only problem is that none of us can program for Windows (I assume that `.Net` is required for this, right?)
In any case any community help appreciated, we can help debug / optimize / fix the models.

**Comment by studennikov-serg** [comment]
Yes, may require .net for NL. Also native dll wrapper and python runtime.
I'll test demo on Windows...

**Comment by snakers4** [comment]
We could not port to ONNX
Maybe since there are very little actual dependencies
You could just pigg-back on PyTorch builds for Windows?

**Comment by snakers4** [comment]
I briefly talked to the RHvoice team manager, the gist is that for this use case very low latency is a must

 I.e. less than 100ms for any short utterance

Now this may be less achievable w/o GPU

We need 10+ RTS on a single CPU thread to make this possible 

Technically just pulling a PyTorch  build for windows should not be a problem

**Comment by studennikov-serg** [comment]
Windows build works! But unable to save audio: "AttributeError: 'list' object has no attribute 'ndim'".

I'm not a Python writer, if someone will able to send audio to sound card, we may move forward

**Comment by snakers4** [comment]
I have never handled audio playback with python (we do not work on local machines usually).
There some easy googleable [guidelines ](https://realpython.com/playing-and-recording-sound-python/#playing-audio-files) - but I simply do not know which way is the most proper way

> Windows build works! But unable to save audio: "AttributeError: 'list' object has no attribute 'ndim'".

But this snippet may help to deal with the list of tensors using `torchaudio`:

```python
import torchaudio

for i, _audio in enumerate(audio):
  torchaudio.save(f'test_{str(i).zfill(2)}.wav',
                  audio[0].unsqueeze(0),
                  sample_rate=16000,
                  bits_per_sample=16)
```

You see, the pipeline returns a list of tensors. Each tensor is 1D float tensor of audio samples.
Usually 95% of python libraries like to work with numpy arrays, so you may have to do something like this instead not to install `torchaudio`, which is heavy:

```python
from scipy.io.wavfile import write

for i, _audio in enumerate(audio):
  write(f'test_{str(i).zfill(2)}.wav',
           rate=16000,
           data=_audio.numpy())
```

**Comment by snakers4** [comment]
The only problem may be that the resulting file may contain `float32` values instead of `int16` values
In this case you may do something like this:

```
from scipy.io.wavfile import write

def float_to_int(wav):
  wav *= 32767
  wav = wav.astype('int16')
  return wav

for i, _audio in enumerate(audio):
  write(f'test_{str(i).zfill(2)}.wav',
        rate=16000,
        data=float_to_int(_audio.numpy()))
```

**Comment by studennikov-serg** [comment]
I tried direct way:
torchaudio.save('C:/t.wav', audio, sample_rate)

Your code says:
write(f'c:/test_{str(i).zfill(2)}.wav',
wavfile.py", line 760, in write
dkind = data.dtype.kind
AttributeError: 'NoneType' object has no attribute

How do you write on this lang...Something like GW basic from 80th:)
I'll try something later.

**Comment by snakers4** [comment]
I am not sure that I undestand your error since you do not provide the full error message / reproducible code snippet, but just check out the docs for a corresponding verison of `torchaudio`

Also looks like you are not providing all of the params to the `save` function

**Comment by studennikov-serg** [comment]
The snippet that you gave as an example does not work.
All parameters are in place, taken from the documentation.

**Comment by snakers4** [comment]
It is strange since I copy-pasted snippets from colab after testing them
Plz contact me directly in telegram if that is easier
