### ISSUE TITLE
❓ Audio sample for "Thorsten" dataset is published

### ISSUE THREAD

**Issue by thorstenMueller** [snakers4/silero-models#65]
## Thanks @snakers4 for training a model on "Thorsten" dataset

I just wanted to inform you that i've syntesized some comparison samples with your notebook and uploaded them on my audio comparison page.

https://thorstenmueller.github.io/deep-learning-german-tts/audio_compare#silero-models

Hope that's okay for you.

Thanks for your support and have a nice day :-)

Thorsten

**Comment by snakers4** [comment]
Cool, many thanks

**Comment by thorstenMueller** [comment]
My pleasure.
