### ISSUE TITLE
How to get original Pytorch Weights and Source code of the models❓ Questions / Help / Support

### ISSUE THREAD

**Issue by elcronos** [snakers4/silero-models#75]
Hi,

I'm currently researching on robustness of AI systems in sound classification tasks. In order to investigate how the activations some decision are made, I need to be able to modify and access some layer in the model. However, currently the models I get from Pytorch Hub are loaded as ScriptModules. I was wondering if I could get the original code of the network and their corresponding weights as a .pt file. This will help me to carry on with the experiements I need. Of course, I'm happy to cite your work.

**Comment by snakers4** [comment]
Hi @elcronos,

Thank you for your interest

We do not publish the original code intentionally

But for your purposes please check out the `skip` model - it is what you are looking for
