### ISSUE TITLE
Not able to recognize the  numerical voice data.

### ISSUE THREAD

**Issue by data-scientist-2020** [snakers4/silero-models#82]
Hi Team,

I am using this model for recognizing the 16 digits credit card number  from the audio files. But among the 16 digits number  I am able to recognize mostly 12 digits and rest are not. I am using the indian accent english `voice. The code what I am using is below

import torch
import zipfile
import torchaudio
from glob import glob
import warnings
warnings.filterwarnings("ignore")

def transcript(audio_path):
	digits=[]
	device = torch.device('cpu')  # gpu also works, but our models are fast enough for CPU

	model, decoder, utils = torch.hub.load(repo_or_dir='snakers4/silero-models',
	                                       model='silero_stt',
	                                       language='en', # also available 'de', 'es'
	                                       device=device)
	(read_batch, split_into_batches,
	 read_audio, prepare_model_input) = utils  # see function signature for details

	# download a single file, any format compatible with TorchAudio (soundfile backend)
	# torch.hub.download_url_to_file('https://opus-codec.org/static/examples/samples/speech_orig.wav',
	#                                dst ='speech_orig.wav', progress=True)

	char_map={
		'zero' : '0',
		'one' : '1',
		'two': '2',
		'three' : '3',
		'four' : '4',
		'five' : '5',
		'six' : '6',
		'seven' : '7',
		'eight' : '8',
		'nine' : '9',
		'double': 'double'
	}
	test_files = glob(audio_path)
	batches = split_into_batches(test_files, batch_size=10)
	input = prepare_model_input(read_batch(batches[0]),
	                            device=device)

	output = model(input)
	for example in output:
		number=decoder(example.cpu())
	print(number)

	text= number.split(' ')
	for item in text:

		if item in char_map.keys() or item=='double':
			digits.append(char_map[item])

	number= ' '.join(digits)

	return number

number= transcript('D:\\ML Workspace\\speech-recognition\\test_audio_data\\0.wav')
print(number)

Here in the audio people are mostly using double if the number repeated twice.

**Comment by snakers4** [comment]
> But among the 16 digits number I am able to recognize mostly 12 digits and rest are not

What does this mean?
Can you share an audio and example output?

**Comment by data-scientist-2020** [comment]
[0.wav.zip](https://github.com/snakers4/silero-models/files/6491969/0.wav.zip)

Actual voice output: hello hello i certain can give your datil we ro one one seven seven i page to wait for seven nine one three ok i thank you
Filtered output: 1 1 7 7 2 7 9 1 3

I have provided the required information suggested by you. Please let me know for further details.

thanks

**Comment by snakers4** [comment]
it is expected that the free CE model has errors on a noisy audio with accent
for higher quality / custom models - please reach out for commercial quotes
