### ISSUE TITLE
Please, add a demo

### ISSUE THREAD

**Issue by mariusa** [snakers4/silero-models#92]
## ❓ Questions and Help

We have a [wiki](https://github.com/snakers4/silero-models/wiki) available for our users. Please make sure you have checked it out first.

Please, add a demo. All TTS projects start with a demo of their best results.
eg https://github.com/coqui-ai/TTS

A demo motivates me (or, if it's bad, not) to read further and start investing in the project.

**Comment by snakers4** [comment]
Please kindly make at least some time to read the provided README - https://github.com/snakers4/silero-models#text-to-speech
This section contains plenty of demos

**Comment by mariusa** [comment]
Hi Alexander, I did go through it, twice. That section has "Open in Collab" as the only link, eg
https://colab.research.google.com/github/snakers4/silero-models/blob/master/examples_tts.ipynb

I'm looking for something already recorded/rendered, where one could simply click Play to hear some samples:
![2021-06-25_12-07](https://user-images.githubusercontent.com/1283842/123400055-0469cb00-d5ae-11eb-9fb1-72ff16a3330f.png)

**Comment by snakers4** [comment]
I do not really see the problem with the demo that allows you to check the models live by clicking 2 buttons
The example pages typically are cherry picked af and rarely (in case of academia never) updated

For more examples and motivation please see these

- https://habr.com/ru/post/549482/
- https://habr.com/ru/post/563484/
